### ISSUE TITLE
value of dt

### ISSUE THREAD

**Issue by keirymb** [goktug97/DynamicWindowApproach#5]
I want to know why 𝑑𝑡 can't be lower than 0.1? As soon as I use a value lower than 0.1 for 𝑑𝑡, the simulation no longer works. Can someone explain to me why it doesn't work? It is important to note that I am using the Python demo example.

**Comment by goktug97** [comment]
It should work. Maybe also lower the `yawrate_resolution` and `velocity_resolution`.

**Comment by keirymb** [comment]
Yes, that helped. 

Thank you
